name: Python Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mysql-connector-python
        # Add any other dependencies your project needs
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run unit tests
      run: |
        # Add the project root to PYTHONPATH to resolve import issues
        export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}
        pytest streamlit/tests/
      env:
        PYTHONPATH: ${{ github.workspace }}